---
title: ""
---

<style>
body {
text-align: justify}
</style>


## Published/Accepted Papers

Li, L., Hrozencik, A.R., **Rouhi Rad, M.**, Uz, D., ["The Impacts of Depopulation and Climate Change on the Cost of Rural Electric Services."](https://www.sciencedirect.com/science/article/pii/S0095069625001391) *Journal of Environmental Economics and Management*, 135:103255 (2025).

Medina, N., **Rouhi Rad, M.**, Nozari, S., Suter, J.F., Bailey, R.T., Sahoo, D., ["Water Scarcity Exacerbates the Negative Effects of Salinity on Irrigated Agriculture."](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2024WR038504) *Water Resources Research*, 61(11), e2024WR038504 (2025).

**Rouhi Rad, M.**, Suter, J.F., Manning, D.T., and Goemans, C., ["Abatement Subsidies for Groundwater Conservation."](https://onlinelibrary.wiley.com/doi/10.1111/ajae.70021) *American Journal of Agricultural Economics* (2025).

Bahrami, S., **Rouhi Rad, M.**, and Nayga, R.M., ["Dollars for Drops: Abatement Cost of Water for Irrigation in the Colorado River Basin."](https://onlinelibrary.wiley.com/doi/10.1002/aepp.70026) *Applied Economic Perspectives and Policy* (2025).

**Rouhi Rad, M.**, Li, L., Woodward, R.T., ["Non-Market Valuation of Environmental Resources: An Introduction."](https://oxfordre.com/economics/) *Oxford Research Encyclopedia of Economics and Finance* (2025).

Busari, I., Sloggy, M.R., **Rouhi Rad, M.**, Sahoo, D., Drury, S.A., and Escobedo, F.J., ["Modeling Wildfire Effects on Ecosystem Services in two Disparate California Watersheds and Communities."](https://doi.org/10.1007/s00267-025-02185-3) *Environmental Management* (2025).

Bahrami, S., **Rouhi Rad, M.**, Nayga, R., ["Land Tenure and Conservation in Agriculture: Evidence from United States Farm-level Data."](https://doi.org/10.1016/j.landusepol.2025.107534) *Land Use Policy*, 153, p.107534 (2025).

Nozari, S., Bailey, R.T., **Rouhi Rad, M.**, Smith, G.E., Andales, A.A., Zambreski, Z.T., Tavakoli-Kivi, S., Sharda, V., Kisekka, I., Gowda, P., and Schipanski, M.E., ["An Integrated Modeling Approach to Simulate Human-Crop-Groundwater Interactions in Intensively Irrigated Regions."](https://doi.org/10.1016/j.envsoft.2024.106120) *Environmental Modelling & Software* (2024).

Guerrero, V.L., Sahoo, D., Dickes, L., Walker, T., **Rouhi Rad, M.**, and Allen, J., ["Adaptive Water Governance in an Interest-Based Stakeholder-Driven Water Resource Planning Institution in South Carolina, US."](https://ascelibrary.org/doi/10.1061/JWRMD5.WRENG-6180) *Journal of Water Resources Planning and Management*, 150(6) (2024).

**Rouhi Rad, M.**, Mieno, T., & Brozović, N., ["The Role of Search Frictions and Trading Ratios in Tradable Permit Markets."](https://link.springer.com/article/10.1007/s10640-022-00664-3) *Environmental and Resource Economics*, 82(1), 101-132 (2022).

Mieno, T., **Rouhi Rad, M.**, Suter, J.F., Hrozencik, A., ["The Importance of Well Yield in Groundwater Demand Specifications."](http://le.uwpress.org/content/97/3/672.abstract) *Land Economics*, 97(3), 672-687 (2021).

Sloggy, M., Suter, J.F., **Rouhi Rad, M.**, Manning, D.T., Goemans, C., ["Changing climate, changing minds? The effects of natural disasters on public perceptions of climate change."](https://link.springer.com/article/10.1007/s10584-021-03242-6) *Climatic Change*, 168 (2021).

**Rouhi Rad, M.**, Adamowicz, W., Entem, A., Fenichel, E.P., Lloyd-Smith, P., ["Complementarity (Not Substitution) Between Natural and Produced Capital."](https://www.journals.uchicago.edu/doi/10.1086/714675) *Journal of the Association of Environmental and Resource Economists*, 8(6), 1115-1146 (2021).

**Rouhi Rad, M.**, Manning, D.T., Suter, J.F., Goemans, C., ["Policy Leakage or Policy Benefit? Spatial Spillovers from Conservation Policies in Common Property Resources."](https://www.journals.uchicago.edu/doi/10.1086/714148) *Journal of the Association of Environmental and Resource Economists*, 8(5), 923-953 (2021).

Li, L., Long, D., **Rouhi Rad, M.**, Sloggy, M., ["Stay-at-home orders and the willingness to stay home during the COVID-19 pandemic: A stated-preference discrete choice experiment."](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0253910) *PLOS ONE*, 16(7), e0253910 (2021).

Lloyd-Smith, P., Adamowicz, W., Entem, A., Fenichel, E.P., **Rouhi Rad, M.**, ["The Decade after Tomorrow: Estimation of Discount Rates from Realistic Temporal Decisions."](https://www.sciencedirect.com/science/article/abs/pii/S0167268120304686) *Journal of Economic Behavior and Organization*, 183, 158-174 (2021).

Araya, A., Gowda, P.H., **Rouhi Rad, M.**, Ariyaratne, C.B., Ciampitti, I.A., Rice, C.W., & Prasad, P.V.V., ["Evaluating optimal irrigation for potential yield and economic performance of major crops in southwestern Kansas."](https://doi.org/10.1016/j.agwat.2020.106536) *Agricultural Water Management*, 244, 106536 (2021).

Suter, J.F., **Rouhi Rad, M.**, Manning, D.T., Goemans, C., ["Groundwater depletion, climate, and the value of groundwater conservation."](https://www.sciencedirect.com/science/article/abs/pii/S0928765518303403) *Resource and Energy Economics*, 63, 101143 (2021).

Manning, D.T., **Rouhi Rad, M.**, Suter, J.F., Goemans, C., ["Non-market valuation in integrated modeling: The benefits of water right retirement."](https://www.sciencedirect.com/science/article/pii/S0095069620300644) *Journal of Environmental Economics and Management*, 103, 102341 (2020).

**Rouhi Rad, M.**, Araya, A., Zambreski, Z.T., ["Downside Risk of Aquifer Depletion."](https://link.springer.com/article/10.1007/s00271-020-00688-x) *Irrigation Science*, 38(5), 577-591 (2020).

**Rouhi Rad, M.**, Haacker, E.M.K., Sharda, V., Nozari, S., Xiang, Z., Araya, A., Uddameri, V., Suter, J.F., Gowda, P., ["MOD\$\$AT: A hydro-economic model for aquifer management in agriculture."](https://www.sciencedirect.com/science/article/abs/pii/S0378377419317032) *Agricultural Water Management*, 238, 106194 (2020).

**Rouhi Rad, M.**, Brozović, N., Foster, T., and Mieno, T., ["Effects of instantaneous groundwater availability on irrigated agriculture and implications for aquifer management."](https://www.sciencedirect.com/science/article/pii/S0928765518303816) *Resource and Energy Economics*, 59, 101129 (2020).

Adamowicz, W., Calderon-Etter, L., Entem, A., Fenichel, E.P., Hall, J.S., Lloyd-Smith, P., Ogden, F.L., Regina, J.A., **Rouhi Rad, M.**, and Stallard, R.F., ["Assessing Ecological Infrastructure Investments."](https://www.pnas.org/content/early/2019/01/04/1802883116) *Proceedings of the National Academy of Sciences*, 116(12), 5254-5261 (2019).

**Rouhi Rad, M.**, Book review: ["The Water Problem: Climate Change and Water Policy in the United States."](https://ideas.repec.org/a/wsi/wepxxx/v04y2018i03ns2382624x18800024.html). *Water Economics and Policy*, (2018).

Hurd, B., & **Rouhi Rad, M.**, ["Estimating Economic Effects of Changes in Climate and Water Availability."](https://wordpress.nmsu.edu/bhurd/files/2017/01/J-24-Hurd-and-Rouhi-Rad-2012-Estimating-economic-effects-of-changes-in-climate-and-water-availability-Climatic-Change.pdf) *Climatic Change*, 117(3), 575-584 (2013).

***

## Under Review/Revise and Resubmit

Bahrami, S., **Rouhi Rad, M.**, Hrozencik, R.A., Perez Quesada, G., Nayga, R.M., "The Value of Water Access Security in Agriculture." *Revisions requested at Journal of Environmental Economics and Management*.

Kang, N., **Rouhi Rad, M.**, Nayga, R., Hrozencik, A.R., Perez-Quesada, G., "Impact of the Reclamation Act on Agricultural Development and Population Dynamics in the Western United States." *Revisions requested at American Journal of Agricultural Economics*.

Nozari, S., Bailey, R.T., **Rouhi Rad, M.**, et al., "Groundwater Management Amidst a Changing Climate: A More Severe Climate Can Decrease the Value of Groundwater Conservation." *Revisions submitted at Water Resources Research*.

Bahrami, S., **Rouhi Rad, M.**, Hrozencik, R.A., Perez Quesada, G., Nayga, R.M., "Well Worth It: Well Capacity and the Cost of Aquifer Depletion for Irrigated Agriculture." *Under review*.

Manning, D.T., **Rouhi Rad, M.**, Ogle, S., "Greenhouse Gas Abatement Supply on Agricultural Land." *Under review*.

Judd, R., **Rouhi Rad, M.**, "Regulating Non-Point Source Pollution: Evidence from the Municipal Separate Storm Sewer System Policy." *Under review*.

Donahue, H., Perez Quesada, G., **Rouhi Rad, M.**, Hrozencik, R.A., Nayga, R.M., "Irrigation Organizations in the Western US: Adapting to Water Scarcity." *Under review*.

Uz, D., Hrozencik, A.R., **Rouhi Rad, M.**, Li, L., "Wired for Water: Climate Change and Electricity Use for Irrigation." *Reject and Resubmit*.

Anand, H., **Rouhi Rad, M.**, Shafiee-Jood, M., Alemazkoor, N., "Detecting the Signal: Causal Evidence on the Effectiveness of Hurricane Evacuation Orders." *Reject and Resubmit*.

***

## Working Papers

Yang, W., **Rouhi Rad, M.**, Bahrami, S., Hrozencik, A., Nayga, R., "The Value of Improving Canal Conveyance Efficiency."

**Rouhi Rad, M.**, Abella-Gutierrez, J., Bahrami, S., Banner, J., Cook, M., Dessler, A., et al., "Economic Costs of the Summer 2023 Heat Wave and Drought on Texas."

***
